//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Cake_Image : INotifyPropertyChanged
    {
        public int ID_Cake { get; set; }
        public int Ordinal_Number { get; set; }
        public string Link_Image { get; set; }
        public Nullable<int> Is_Active { get; set; }

        public virtual Cake Cake { get; set; }

        //For Coppy
        public string ImageSource { get; set; }
        public int ImageIndex { get; set; }

        //For Update
        public event PropertyChangedEventHandler PropertyChanged;
    }
}