//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CakeShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string about_page_upper {
            get {
                return ResourceManager.GetString("about_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD JOURNEY.
        /// </summary>
        public static string add_journey_page_upper {
            get {
                return ResourceManager.GetString("add_journey_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SITE.
        /// </summary>
        public static string add_site_page_upper {
            get {
                return ResourceManager.GetString("add_site_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string help_page_upper {
            get {
                return ResourceManager.GetString("help_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string home_page_upper {
            get {
                return ResourceManager.GetString("home_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hiển thị Splash Screen khi khởi chạy ứng dụng vào lần tới..
        /// </summary>
        public static string message_not_show_splash {
            get {
                return ResourceManager.GetString("message_not_show_splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Split là một ứng dụng được viết bằng công nghệ WPF của Microsoft giúp bạn có thể dễ quản lí chuyến đi, bao gồm các công việc như xem tiến độ, hình ảnh, thống kê thu, chi và chia tiền giữa các thành viên..
        /// </summary>
        public static string text_about_app {
            get {
                return ResourceManager.GetString("text_about_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Danh sách trên được sắp xếp tăng dần theo MSSV..
        /// </summary>
        public static string text_about_sort {
            get {
                return ResourceManager.GetString("text_about_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh viên đang học môn Lập trình Windows - Thầy Trần Duy Quang, khoa Công nghệ thông tin, Trường Đại học Khoa học tự nhiên, ĐHQG TP.Hồ Chí Minh..
        /// </summary>
        public static string text_about_us {
            get {
                return ResourceManager.GetString("text_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thắc mắc về ứng dụng xin vui lòng liên hệ wesplit.hcmus@gmail.com.
        ///The MIT License (MIT).
        ///Copy right © 2020 Quoc Thuan Truong, Le Nhat Tuan, Hoang Thi Thuy Trang..
        /// </summary>
        public static string text_contact {
            get {
                return ResourceManager.GetString("text_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/QuocThuanTruong/WeSplit.
        /// </summary>
        public static string text_github {
            get {
                return ResourceManager.GetString("text_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứa thông tin về ứng dụng dụng và các thành viên phát triển..
        /// </summary>
        public static string text_help_about {
            get {
                return ResourceManager.GetString("text_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thẻ thêm chuyến của mình vào danh sách bằng cách điền đầy đủ thông tin và hình ảnh vào trang này. Các thông tin đó bao gồm tên chuyến đi, điểm xuất phát, điểm đến, thông tin lộ trình ,danh sách thành viên và các chi phí cho chuyến đi..
        /// </summary>
        public static string text_help_add_journey {
            get {
                return ResourceManager.GetString("text_help_add_journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi bạn có thể xem và thêm các địa danh du lịch bao gồm các thông tin như tên địa danh, địa chỉ, mô tả và ảnh đại diện..
        /// </summary>
        public static string text_help_add_site {
            get {
                return ResourceManager.GetString("text_help_add_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp thông tin về các trang và hướng dẫn bạn sử dụng We Split..
        /// </summary>
        public static string text_help_help {
            get {
                return ResourceManager.GetString("text_help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng thanh tìm kiếm để tìm chuyến đi mà bạn muốn theo tên chuyến đi, tên địa danh hoặc tên thành viên trong nhóm. Ngoài ra bạn có thể sử dụng các chế độ sắp xếp, chế độ hiển thị của danh sách món ăn và bộ lọc các món ăn theo nhóm để tìm kiếm nhanh hơn.
        ///Mẹo tìm kiếm từ khóa: Bạn có thể sử dụng cú pháp “&lt;key_word_1&gt;” &lt;operator&gt; &lt;”key_word_2&gt;” với &lt;operator&gt; có thể là ‘and’, ‘or’ hoặc ‘and not’ để tìm kiếm.
        ///Sau khi tìm được chuyến đi bạn có thể click vào để xem chi tiết chuyến đi đó. Bên trong mỗi chuyến  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string text_help_home {
            get {
                return ResourceManager.GetString("text_help_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=bOr5t7jbtw8.
        /// </summary>
        public static string text_link_video_help {
            get {
                return ResourceManager.GetString("text_link_video_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120605.
        /// </summary>
        public static string text_mssv_ht {
            get {
                return ResourceManager.GetString("text_mssv_ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120632.
        /// </summary>
        public static string text_mssv_nt {
            get {
                return ResourceManager.GetString("text_mssv_nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120583.
        /// </summary>
        public static string text_mssv_qt {
            get {
                return ResourceManager.GetString("text_mssv_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàng Thị Thùy Trang.
        /// </summary>
        public static string text_name_ht {
            get {
                return ResourceManager.GetString("text_name_ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lê Nhật Tuấn.
        /// </summary>
        public static string text_name_nt {
            get {
                return ResourceManager.GetString("text_name_nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc Thuận Trương.
        /// </summary>
        public static string text_name_qt {
            get {
                return ResourceManager.GetString("text_name_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW DETAIL.
        /// </summary>
        public static string text_view_detail {
            get {
                return ResourceManager.GetString("text_view_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỀ ỨNG DỤNG CAKE SHOP.
        /// </summary>
        public static string title_about_app {
            get {
                return ResourceManager.GetString("title_about_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỀ CHÚNG TÔI.
        /// </summary>
        public static string title_about_us {
            get {
                return ResourceManager.GetString("title_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string title_contact {
            get {
                return ResourceManager.GetString("title_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN SỬ DỤNG CAKE SHOP.
        /// </summary>
        public static string title_how_to_use {
            get {
                return ResourceManager.GetString("title_how_to_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK HƯỚNG DẪN CHI TIẾT.
        /// </summary>
        public static string title_link_how_to_use {
            get {
                return ResourceManager.GetString("title_link_how_to_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK VIDEO.
        /// </summary>
        public static string title_link_video {
            get {
                return ResourceManager.GetString("title_link_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÃ NGUỒN MỞ.
        /// </summary>
        public static string title_open_source {
            get {
                return ResourceManager.GetString("title_open_source", resourceCulture);
            }
        }
    }
}
